Added v2 Items endpoints
Redsauce/RSM-Core pull request #37
Opened 2023-06-21 09:40 UTC by FrostShadow6

2023-06-29 09:29 UTC, ser6l0 requested changes

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +if (isset($requestBody->includeCategories) && $requestBody->includeCategories) {
$requestBody->includeCategories se debe hacer comprobacion estricta de que sea true, si no tambien aceptamos "patata" o cualquier valor que PHP considere como true

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +if (isset($requestBody->translateIDs)) {
$requestBody->translateIDs se debe hacer comprobacion estricta de que sea true, si no tambien aceptamos "patata" o cualquier valor que PHP considere como true

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +if ($IDs != '') {
Deberiamos comprobar si es un array vacío, no una cadena vacía

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +if ($filterRules != '') {
Deberiamos comprobar si es un array vacío, no una cadena vacía

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +        $filterProperties[] = array('ID' => parsePID($rule->propertyID, $clientID), 'value' => replaceUtf8Characters($rule->value), 'mode' => $rule->operation);
sanitizar las variables antes de usarlas

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +if ($extFilterRules != '') {
Deberiamos comprobar si es un array vacío, no una cadena vacía

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +        $formattedExtFilterRules  .=  $singleRule->propertyID . ";" . base64_encode($singleRule->value) . ";" . $singleRule->operation . ',';
sanitizar las variables antes de usarlas

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +    $formattedExtFilterRules = substr_replace($formattedExtFilterRules, "", -1);
es mas optimo usar substr_replace que rtrim? saltaría un warning si la cadena está vacía? comprobarlo

2023-06-29 09:29 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +    checkIsInteger($body->itemTypeID);
Aqui validamos el formato de los tres parametros, en los ejemplos se permite recibir solo 2 de los parametros, ese caso no funcionaría con estas condiciones

2023-06-30 12:11 UTC, FrostShadow6 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +        $values[$propertyID] = 'No CREATE permissions for this property';
No podemos salir porque nos interesa comprobar los permisos de cada property y devolver al usuario los detalles de cada una (si el debug está en true)
![permissions](https://github.com/Redsauce/RSM-Core/assets/43846469/83e10664-601c-4239-ae7b-32eede920e18)

2023-06-30 12:14 UTC, FrostShadow6 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +    $newID = createItem($clientID, $correctProperties);
En principio se acordó que aunque no todos los items se puedan crear, si en lo que le pasamos hay algunos que sí, esos se van a crear mientras que los otros no. Como ejemplo tenemos la imagen:
![permissions](https://github.com/Redsauce/RSM-Core/assets/43846469/c7733a90-50cc-409d-8682-28002041ffb5)

2023-06-30 12:17 UTC, FrostShadow6 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +  } else {
No podemos salir del loop porque tenemos que recorrer todos los items que se nos envían

2023-06-30 14:22 UTC, FrostShadow6 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/get.php
> +    $formattedExtFilterRules = substr_replace($formattedExtFilterRules, "", -1);
Correcto, es mejor rtrim, lo cambiamos. Además rtrim no da problemas si llega un string vacío.

2023-07-05 09:41 UTC, closed without merging