Added create.php
Redsauce/RSM-Core pull request #40
Opened 2023-07-05 10:43 UTC by FrostShadow6

2023-07-06 08:44 UTC, ser6l0 requested changes

2023-07-06 08:44 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +    if ($RSallowDebug) {
lo lógico es poner el if fuera y el foreach dentro para solo comprobar el rsallowdebug una vez

2023-07-06 08:44 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +      $values[$property['ID']] = "Permissions OK";
No tiene sentido devolver siempre todas las propiedades con un "permission OK" ya que el cliente ya conoce las propiedades que ha enviado y si alguna no tiene permisos se va a devolver un 400, se puede eliminar todo el bucle

2023-07-06 08:44 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +  array_push($responseArray, $values);
aqui es mejor usar $responseArray[] = $values;

2023-07-06 08:44 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +if (!empty($responseArray)) {
Que pasa si $responseArray es empty? que devuelve el php?

2023-08-17 14:12 UTC, ser6l0 requested changes

2023-08-17 14:12 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/create.php
> +$responseArray = [];
Aqui estamos vaciando el contenido de responseArray, con lo que perdemos todos los ids almacenados, hay que borrar esta linea

2023-09-14 08:24 UTC, ifernandez approved these changes

2023-09-14 08:25 UTC, ser6l0 approved these changes

2023-09-14 08:25 UTC, merged