New endpoint getTypes for apiV2
Redsauce/RSM-Core pull request #52
Opened 2024-02-07 10:10 UTC by JavieraMaltas

2024-02-07 18:48 UTC, ifernandez requested changes

2024-02-07 18:48 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getTypes.php
> +    $RSallowDebug ? returnJsonMessage(404, 'No ItemTypeIDs were found') : returnJsonMessage(404, '');
Si no hay item types debe devolverse un 200, no un 404. Igualmente, la respuesta debería ser un JSON en ambos casos.

2024-02-08 12:17 UTC, ifernandez requested changes

2024-02-08 12:17 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getTypes.php
> +//            ?ID=6,7,8
Other PHPs get the parameters from the body and not from the URL. I think all PHPs should work in the same way, so there should be a JSON structure in the body

2024-02-08 12:18 UTC, ser6l0 requested changes

2024-02-08 12:18 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getTypes.php
> +if (!isset($_GET['ID']) && empty($_GET['ID'])) {
Esta validación no tiene sentido, si no está definido, por que además validamos que esté vacío? puede que sea un "or" en vez de un "and"?

2024-02-08 12:18 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getTypes.php
> +        array_push($responseArray, $combinedArray);
No tiene sentido que te devuelva el itemtype si no tiene permiso para leer ninguna de sus propiedades

2024-02-08 12:18 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getTypes.php
> +    $itemTypeIDName = getClientItemTypeName($itemTypeID, $clientID);
Yo validaría primero si el usuario tiene permiso para alguna propiedad y sólo en ese caso obtendría el itemtype name

2024-02-16 08:21 UTC, ser6l0 approved these changes

2024-02-16 08:21 UTC, merged