Added endpoint
Redsauce/RSM-Core pull request #55
Opened 2024-02-28 13:29 UTC by FrostShadow6

2024-03-12 17:24 UTC, ifernandez requested changes

2024-03-12 17:24 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +$RSuserID =  getRSuserID();
```suggestion
$RStoken = getRStoken();
$RSuserID = getRSuserID();
```

2024-03-12 17:24 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +//translateIDs
```suggestion
// translateIDs
```

2024-03-12 17:24 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +    returnJsonMessage(200, '');
Add a debug mode clause to get more details in the log or in the answer, if debug mode is enabled

2024-03-12 17:24 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +        returnJsonMessage(404, '');
This should return 200

2024-03-12 17:24 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +    //single item identified, return it as usual for backwards compatibility
```suggestion
    // single item identified, return it as usual for backwards compatibility
```

2024-03-13 08:08 UTC, ifernandez requested changes

2024-03-13 08:08 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +                'propertyID'    => $property['id'],
```suggestion
                'propertyID' => $property['id'],
```

2024-03-13 08:08 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +        // fix the id vs ID key issue TODO: review all code and solve it
What does this mean? Is there some pending work in the file?

2024-03-13 08:09 UTC, ser6l0 requested changes

2024-03-13 08:16 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/items/getItemFromProperty.php
> +        returnJsonMessage(404, "Item doesn't exist");
returnJsonMessage(404, "Source item with ID " . $filterPropertyID . " does not exist");

2024-03-13 08:17 UTC, ser6l0 requested changes
Additional comment for line 59

2024-03-13 15:09 UTC, ser6l0 approved these changes

2024-03-13 15:09 UTC, merged