added endpoints
Redsauce/RSM-Core pull request #60
Opened 2024-03-15 13:36 UTC by FrostShadow6

2024-03-26 10:38 UTC, ifernandez requested changes

2024-03-26 10:38 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/staff/get.php
> +    returnJsonMessage(200, 'No users found');
```suggestion
    returnJsonMessage(200, 'No user found');
```

2024-03-26 10:38 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/staff/get.php
> +  checkBodyContains($body, 'clientID');
Con la API no vamos a saber el client ID. Hemos de deducir el client ID del token. Este archivo ha de recibir el token.

2024-03-26 10:38 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/user/get.php
> +    returnJsonMessage(200, 'No users found');
```suggestion
    returnJsonMessage(200, 'No user found');
```

2024-03-26 10:38 UTC, ifernandez commented on Server/htdocs/AppController/commands_RSM/api/v2/user/get.php
> +  checkBodyContains($body, 'clientID');
Con la API no vamos a saber el client ID. Hemos de deducir el client ID del token. Este archivo ha de recibir el token.

2024-03-26 10:38 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/staff/get.php
> +$theQuery = "SELECT RS_ITEM_ID as 'ID' FROM `rs_users` WHERE RS_LOGIN = '" . $login . "' AND RS_PASSWORD = '" . $password . "' AND RS_CLIENT_ID = '" . $clientID . "'";
Hay que asegurar que sanitizamos todos los parámetros de entrada (body) para evitar SQL injection y otros posibles ataques (hay que hacerlo de forma genérica para que aplique a todos los PHPs)

2024-03-26 10:38 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/staff/get.php
> +<?php
describir que hace el PHP, y parámetros de entrada y salida

2024-03-26 10:38 UTC, ser6l0 commented on Server/htdocs/AppController/commands_RSM/api/v2/user/get.php
> +<?php
describir que hace el PHP, y parámetros de entrada y salida

2024-03-26 10:39 UTC, ser6l0 requested changes
Review comments

2024-05-17 09:23 UTC, ifernandez approved these changes

2024-05-17 09:24 UTC, ser6l0 approved these changes

2024-05-17 09:25 UTC, merged