RSM Core: added functionality to return the item type icon
Redsauce/RSM-Core pull request #73
Opened 2024-07-02 16:45 UTC by ifernandez

This is for the  init functions of the class data manager

2024-07-03 06:24 UTC, alfonsoabas approved these changes

2024-07-09 08:57 UTC, pgomez-redsauce requested changes
There is one typo in two files required to be fixed.

2024-07-09 08:57 UTC, pgomez-redsauce commented on Server/htdocs/AppController/commands_RSM/shared/classDataManager_init.php
> +$itemTytpeIcon       = getClientItemTypeIcon($itemTypeID    , $clientID);
Here there is a typo: "Tytpe" instead of "Type"

2024-07-09 08:57 UTC, pgomez-redsauce commented on Server/htdocs/AppController/commands_RSM/shared/classDataManager_init2.php
> +$itemTytpeIcon       = getClientItemTypeIcon         ($itemTypeID    , $clientID);
Same typo: $itemTytpeIcon should be $itemTypeIcon

2024-07-09 15:19 UTC, alfonsoabas approved these changes

2024-07-10 04:49 UTC, pgomez-redsauce requested changes
Typo fixed :)

2024-07-10 04:50 UTC, pgomez-redsauce approved these changes

2024-07-14 19:36 UTC, merged